---
- hosts: all
  become: true
  pre_tasks:
    - name: force APT cache update
      apt:
        update_cache: yes

  tasks:
    - name: install tools
      package:
        name: "{{ item }}"
      with_items:
        - git

    - name: ensure submodules are initialized
      command: git submodule update --init
      args:
        chdir: "{{ oswatcher_path }}"
      become: false

    - name: install OSWatcher system dependencies
      package:
        name: "{{ item }}"
      with_items:
        - virtualenv
        - python3-virtualenv
        - libguestfs0
        - libguestfs-dev
        - python3-guestfs
        - python3-dev
        - pkg-config
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: create oswatcher virtualenv
      command: virtualenv --system-site-packages -p python3 venv
      args:
        chdir: /home/vagrant
        creates: venv
      become: false

    - name: install oswatcher pip dependencies
      command: ./venv/bin/pip install -r {{ oswatcher_path }}/requirements.txt
      args:
        chdir: /home/vagrant
      become: false

    - name: install XFCE desktop
      package:
        name: "{{ item }}"
      with_items:
        - xfce4
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: install virt-manager and libvirt
      package:
        name: "{{ item }}"
      with_items:
        - virt-manager
        - libvirt-daemon-system
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: start libvirt
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: download Packer
      get_url:
        url: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
        dest: /tmp/packer.zip
      become: false

    - name: extract Packer
      unarchive:
        src: /tmp/packer.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: remove packer.zip
      win_file:
        path: /tmp/packer.zip
        state: absent

    - name: fix permissions on kvm node
      file:
        path: /dev/kvm
        mode: 0666

    - name: clone packer templates
      git:
        repo: https://github.com/Wenzel/packer-templates
        dest: /home/vagrant/packer-templates
      become: false

    - name: Build Windows XP
      command: packer build -var-file winxp.json windows.json
      args:
        chdir: /home/vagrant/packer-templates
      become: false

    - name: get qcow name
      find:
        path: "/home/vagrant/packer-templates/output-qemu"
      register: qemu_output

    - name: install import_libvirt.py deps
      package:
        name: "{{ item }}"
      with_items:
        - python3-docopt
        - python3-lxml
        - python3-libvirt
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: Import Windows XP in Libvirt
      win_command: "./import_libvirt.py --open-vnc {{ qemu_output.files[0].path }}"
      args:
        chdir: /home/vagrant/packer-templates
