---
- hosts: all
  become: true
  pre_tasks:
    # vagrant bug: https://github.com/hashicorp/vagrant/issues/11279
    # - name: check for virtualization extensions in cpuinfo
    #   shell: egrep '(vmx|svm)' /proc/cpuinfo
      
    - name: system upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted

  tasks:
    - name: install tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - python3-apt
        - software-properties-common

    - name: add repo for Python 3.7
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: install python 3.7
      package:
        name: "{{ item }}"
      with_items:
        - python3.7

    - name: ensure submodules are initialized
      command: git submodule update --init
      args:
        chdir: "{{ oswatcher_path }}"
      become: false

    - name: install OSWatcher system dependencies
      package:
        name: "{{ item }}"
      with_items:
        - virtualenv
        - python3-virtualenv
        - libguestfs0
        - libguestfs-dev
        - python3-guestfs
        - python3-dev
        - pkg-config
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: create oswatcher virtualenv
      command: virtualenv --system-site-packages -p python3 venv
      args:
        chdir: /home/vagrant
        creates: venv
      become: false

    - name: install oswatcher pip dependencies
      command: ./venv/bin/pip install -r {{ oswatcher_path }}/requirements.txt
      args:
        chdir: /home/vagrant
      become: false

    - name: install XFCE desktop
      package:
        name: "{{ item }}"
      with_items:
        - xfce4
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: install virt-manager and libvirt
      package:
        name: "{{ item }}"
      with_items:
        - virt-manager
        - libvirt-daemon-system
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: start libvirt
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: add current user in libvirt groups
      user:
        name: vagrant
        groups: kvm,libvirt-qemu,libvirt
        append: yes

    # - name: download Packer
    #   get_url:
    #     url: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
    #     dest: /tmp/packer.zip
    #   become: false

    # - name: extract Packer
    #   unarchive:
    #     src: /tmp/packer.zip
    #     dest: /usr/local/bin
    #     remote_src: yes

    # - name: remove packer.zip
    #   file:
    #     path: /tmp/packer.zip
    #     state: absent

    # - name: fix permissions on kvm node
    #   file:
    #     path: /dev/kvm
    #     mode: 0666

    - name: clone packer templates
      git:
        repo: https://github.com/Wenzel/packer-templates
        dest: /home/vagrant/packer-templates
      become: false

    # - name: Build Windows XP
    #   command: packer build -var-file winxp.json windows.json
    #   args:
    #     chdir: /home/vagrant/packer-templates
    #   become: false

    # - name: get qcow name
    #   find:
    #     path: "/home/vagrant/packer-templates/output-qemu"
    #   register: qemu_output

    - name: download winxp image
      get_url:
        url: https://www.dropbox.com/s/0zycew5u3xnf8m7/winxp.qcow2?dl=1
        dest: /home/vagrant/packer-templates/winxp.qcow2
      become: false

    - name: install import_libvirt.py deps
      package:
        name: "{{ item }}"
      with_items:
        - python3-docopt
        - python3-lxml
        - python3-libvirt
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 10
      delay: 10

    - name: define qemu:///session oswatcher pool
      command: virsh -c qemu:///session pool-define-as oswatcher --type dir --target /home/vagrant/images
      become: false

    - name: enable qemu:///session oswatcher pool
      command: virsh -c qemu:///session pool-autostart oswatcher
      become: false

    - name: enable qemu:///session oswatcher pool
      command: virsh -c qemu:///session pool-build oswatcher
      become: false

    - name: enable qemu:///session oswatcher pool
      command: virsh -c qemu:///session pool-start oswatcher
      become: false

    - name: Import Windows XP in Libvirt
      command: "./import_libvirt.py --uri qemu:///session --open-vnc --pool oswatcher /home/vagrant/packer-templates/winxp.qcow2"
      args:
        chdir: /home/vagrant/packer-templates
      become: false
